spring:
  datasource:
      url: jdbc:mysql://localstory.cdlw5k7uqati.ap-northeast-2.rds.amazonaws.com:3306/LocalStory?&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 6397zooOO!
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
      jdbc:
        time_zone: Asia/Seoul
      format_sql: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: always

img:
  path: file:///home/ec2-user/LocalStory/img/
  urlForAccess: /img/**

accessIp: 43.201.18.199

